// Functions library
// Defines custom functions for the template.
// TEMPLATE SPECIFIC FUNCTIONS. DO NOT EDIT THIS FILE DIRECTLY UNLESS YOU KNOW WHAT YOU'RE DOING!

// Template functions now use the XPT tag to differentiate them from functions I write for my own missions. --Superxpdude
class XPT
{
	

	
	
	class system
	{
		file = "template\functions\system";
		class fpsMarkers {postInit = 1;}; 		// Function to place FPS indicators on the map
		class mapMarkersClient {}; 				// Client-side portion of the map-markers module
		class mapMarkersServer {}; 				// Server-side portion of the map-markers module
		
	};
};